// Halo Composer keymap for NuPhy Halo75 V2 (ANSI)
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Same layers as the default keymap; adds a 128-LED g_led_config (keys + halo)
// and hooks the Composer engine into QMK.

#include "../default/keymap.c"
#include "composer/hc_qmk.h"

// tools/make_via_json.py appends Composer as entry 43 of VIA's Effect dropdown.
_Static_assert(RGB_MATRIX_CUSTOM_composer == 43, "Composer moved in the RGB matrix mode list; update make_via_json.py");

// clang-format off
led_config_t g_led_config = {
    {
        {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 14, NO_LED},
        {16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, NO_LED, 30, NO_LED},
        {31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, NO_LED, 45, NO_LED},
        {46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, NO_LED, 58, NO_LED, 59, NO_LED},
        {60, NO_LED, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, NO_LED, 71, 72, 73, NO_LED},
        {74, 75, 76, NO_LED, NO_LED, NO_LED, 77, NO_LED, NO_LED, 78, 79, NO_LED, NO_LED, 80, 81, 82, NO_LED},
    },
    {
        // generated by tools/gen_geometry.py (keys 0..82, halo 83..127)
        {22, 16}, {34, 16}, {46, 16}, {58, 16}, {70, 16}, {82, 16}, {94, 16}, {106, 16}, {118, 16}, {130, 16}, {142, 16}, {154, 16}, {166, 16}, {178, 16}, {202, 16}, {190, 16}, {22, 24}, {34, 24}, {46, 24}, {58, 24}, {70, 24}, {82, 24}, {94, 24}, {106, 24}, {118, 24}, {130, 24}, {142, 24}, {154, 24}, {166, 24}, {184, 24}, {202, 24}, {25, 32}, {40, 32}, {52, 32}, {64, 32}, {76, 32}, {88, 32}, {100, 32}, {112, 32}, {124, 32}, {136, 32}, {148, 32}, {160, 32}, {172, 32}, {187, 32}, {202, 32}, {26, 40}, {43, 40}, {55, 40}, {67, 40}, {79, 40}, {91, 40}, {103, 40}, {115, 40}, {127, 40}, {139, 40}, {151, 40}, {163, 40}, {182, 40}, {202, 40}, {30, 48}, {49, 48}, {61, 48}, {73, 48}, {85, 48}, {97, 48}, {109, 48}, {121, 48}, {133, 48}, {145, 48}, {157, 48}, {174, 48}, {190, 48}, {202, 48}, {24, 56}, {38, 56}, {54, 56}, {98, 56}, {144, 56}, {158, 56}, {178, 56}, {190, 56}, {202, 56}, {14, 5}, {20, 5}, {26, 5}, {32, 5}, {38, 5}, {135, 62}, {146, 62}, {157, 62}, {169, 62}, {180, 62}, {123, 62}, {112, 62}, {101, 62}, {89, 62}, {78, 62}, {67, 62}, {55, 62}, {44, 62}, {33, 62}, {21, 62}, {10, 62}, {2, 56}, {2, 48}, {2, 40}, {2, 32}, {2, 24}, {2, 16}, {2, 8}, {60, 2}, {79, 2}, {97, 2}, {116, 2}, {135, 2}, {153, 2}, {172, 2}, {194, 5}, {206, 5}, {222, 8}, {222, 20}, {222, 32}, {222, 44}, {222, 56}, {214, 62}, {203, 62}, {191, 62}
    },
    {
        // keys = KEYLIGHT; halo = NONE so stock QMK effects leave it to NuPhy's halo engine.
        // The Composer effect ignores flags and drives all 128 LEDs.
        [0 ... 82]   = LED_FLAG_KEYLIGHT,
        [83 ... 127] = LED_FLAG_NONE,
    },
};
// clang-format on

void keyboard_post_init_user(void) {
    hc_init();
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    hc_process_key(record->event.key.row, record->event.key.col, record->event.pressed);
    return true;
}

bool rgb_matrix_indicators_user(void) {
    hc_indicators();
    return true;
}
