#!/usr/bin/env python3
"""Generates Halo75 V2 LED geometry for Halo Composer (firmware C + GUI JSON).

Key positions come from keyboard.json (LAYOUT_ansi_84) mapped into QMK's
224x64 space. Halo positions/ring order are a best-effort INFERENCE from
NuPhy's side.c power-on order + group bitmasks and MUST be verified with the
GUI's calibration wizard on real hardware.
"""
import json, sys, math

KEYS = [(0,'Esc',0,0,1),(1,'F1',1,0,1),(2,'F2',2,0,1),(3,'F3',3,0,1),(4,'F4',4,0,1),(5,'F5',5,0,1),(6,'F6',6,0,1),(7,'F7',7,0,1),(8,'F8',8,0,1),(9,'F9',9,0,1),(10,'F10',10,0,1),(11,'F11',11,0,1),(12,'F12',12,0,1),(13,'PrtSc',13,0,1),(14,'Del',15,0,1),(15,'Ins',14,0,1),
(16,'`',0,1,1),(17,'1',1,1,1),(18,'2',2,1,1),(19,'3',3,1,1),(20,'4',4,1,1),(21,'5',5,1,1),(22,'6',6,1,1),(23,'7',7,1,1),(24,'8',8,1,1),(25,'9',9,1,1),(26,'0',10,1,1),(27,'-',11,1,1),(28,'=',12,1,1),(29,'Bksp',13,1,2),(30,'Home',15,1,1),
(31,'Tab',0,2,1.5),(32,'Q',1.5,2,1),(33,'W',2.5,2,1),(34,'E',3.5,2,1),(35,'R',4.5,2,1),(36,'T',5.5,2,1),(37,'Y',6.5,2,1),(38,'U',7.5,2,1),(39,'I',8.5,2,1),(40,'O',9.5,2,1),(41,'P',10.5,2,1),(42,'[',11.5,2,1),(43,']',12.5,2,1),(44,'\\',13.5,2,1.5),(45,'End',15,2,1),
(46,'Caps',0,3,1.75),(47,'A',1.75,3,1),(48,'S',2.75,3,1),(49,'D',3.75,3,1),(50,'F',4.75,3,1),(51,'G',5.75,3,1),(52,'H',6.75,3,1),(53,'J',7.75,3,1),(54,'K',8.75,3,1),(55,'L',9.75,3,1),(56,';',10.75,3,1),(57,"'",11.75,3,1),(58,'Enter',12.75,3,2.25),(59,'PgUp',15,3,1),
(60,'Shift',0,4,2.25),(61,'Z',2.25,4,1),(62,'X',3.25,4,1),(63,'C',4.25,4,1),(64,'V',5.25,4,1),(65,'B',6.25,4,1),(66,'N',7.25,4,1),(67,'M',8.25,4,1),(68,',',9.25,4,1),(69,'.',10.25,4,1),(70,'/',11.25,4,1),(71,'Shift',12.25,4,1.75),(72,'Up',14,4,1),(73,'PgDn',15,4,1),
(74,'Ctrl',0,5,1.25),(75,'Opt',1.25,5,1.25),(76,'Cmd',2.5,5,1.25),(77,'Space',3.75,5,6.25),(78,'Cmd',10,5,1.25),(79,'Fn',11.25,5,1.25),(80,'Left',13,5,1),(81,'Down',14,5,1),(82,'Right',15,5,1)]
assert len(KEYS) == 83 and all(k[0]==i for i,k in enumerate(KEYS))

def key_xy(k):
    _, _, x, y, w = k
    return (round(16 + (x + w/2) * 12), round(12 + (y + 0.5) * 8))

key_xy_list = [key_xy(k) for k in KEYS]

# --- halo (indices 83..127). Inferred physical ring, clockwise on screen:
H = {}
def line(leds, x0, y0, x1, y1):
    n = len(leds)
    for k, led in enumerate(leds):
        f = 0.5 if n == 1 else k / (n - 1)
        H[led] = (round(x0 + (x1 - x0) * f), round(y0 + (y1 - y0) * f))
front = [125,126,127,92,91,90,89,88] + list(range(93,104))       # 19, right -> left
left  = list(range(104,111))                                     # 7, front -> back
status= list(range(83,88))                                       # 5, top-left surface bar
back  = list(range(111,118))                                     # 7, left -> right
badge = [118,119]                                                # 2, top-right badge (?)
right = list(range(120,125))                                     # 5, back -> front
line(front, 214, 62, 10, 62)
line(left, 2, 56, 2, 8)
line(status, 14, 5, 38, 5)
line(back, 60, 2, 172, 2)
line(badge, 194, 5, 206, 5)
line(right, 222, 8, 222, 56)
assert sorted(H) == list(range(83,128)), sorted(set(range(83,128)) - set(H))
ring_seq = right[2:] + front + left + status + back + badge + right[:2]  # starts at right-middle (angle 0)
assert len(ring_seq) == 45 and len(set(ring_seq)) == 45
ring = {led: (i * 256) // 45 for i, led in enumerate(ring_seq)}
groups = {}
for led in front: groups[led] = 'front'
for led in left: groups[led] = 'left'
for led in right: groups[led] = 'right'
for led in back: groups[led] = 'back'
for led in status: groups[led] = 'status'
for led in badge: groups[led] = 'badge'

halo_xy = [H[i] for i in range(83,128)]
halo_ring = [ring[i] for i in range(83,128)]

def c_arrays():
    out = []
    out.append('// GENERATED by tools/gen_geometry.py - do not edit by hand')
    out.append('#include "hc_engine.h"\n')
    out.append('const uint8_t hc_key_xy[HC_KEY_LEDS][2] = {')
    out.append('    ' + ', '.join('{%d, %d}' % p for p in key_xy_list))
    out.append('};\n')
    out.append('// Halo positions are INFERRED (see docs). Verify with the calibration wizard.')
    out.append('const uint8_t hc_default_halo_xy[HC_HALO_LEDS][2] = {')
    out.append('    ' + ', '.join('{%d, %d}' % p for p in halo_xy))
    out.append('};\n')
    out.append('const uint8_t hc_default_halo_ring[HC_HALO_LEDS] = {')
    out.append('    ' + ', '.join(str(r) for r in halo_ring))
    out.append('};')
    return '\n'.join(out) + '\n'

def g_led_points():
    pts = key_xy_list + halo_xy
    return ', '.join('{%d, %d}' % p for p in pts)

if __name__ == '__main__':
    what = sys.argv[1] if len(sys.argv) > 1 else 'write'
    if what == 'write':
        here = __import__('pathlib').Path(__file__).resolve().parent
        (here.parent / 'composer' / 'hc_board_geometry.c').write_text(c_arrays())
        (here.parent / 'studio' / 'geometry.json').write_text(json.dumps({
            'keys': [{'led': k[0], 'label': k[1], 'x': k[2], 'y': k[3], 'w': k[4], 'px': key_xy_list[k[0]][0], 'py': key_xy_list[k[0]][1]} for k in KEYS],
            'halo': [{'led': 83 + i, 'x': halo_xy[i][0], 'y': halo_xy[i][1], 'ring': halo_ring[i], 'group': groups[83+i]} for i in range(45)],
        }, separators=(',', ':')) + '\n')
        print('wrote composer/hc_board_geometry.c and studio/geometry.json (keymap.c points: run with "points")')
    if what == 'c':
        print(c_arrays(), end='')
    elif what == 'points':
        print(g_led_points())
    elif what == 'json':
        print(json.dumps({
            'keys': [{'led': k[0], 'label': k[1], 'x': k[2], 'y': k[3], 'w': k[4], 'px': key_xy_list[k[0]][0], 'py': key_xy_list[k[0]][1]} for k in KEYS],
            'halo': [{'led': 83 + i, 'x': halo_xy[i][0], 'y': halo_xy[i][1], 'ring': halo_ring[i], 'group': groups[83+i]} for i in range(45)],
        }, separators=(',', ':')))
